#!/usr/bin/env python3
"""
dual_logger.py  —  ONE program, ONE clock, both devices, merged output.

Reads the Arduino current stream and the ESP32 RTD stream at the same time on
one machine, stamps every line with this machine's wall clock, and writes a
single already-merged CSV. Because there is only one clock, there is NO
post-hoc time scaling or phase alignment to do -- the two prior separate
loggers required matching clock rates (the ~0.24% Arduino resonator drift)
and phase; this eliminates both.

Merge policy: emit one merged row per CURRENT sample (preserving the fast
current waveform, including the ~7 A inrush), carrying the most-recent
temperatures forward (sample-and-hold; temps move slowly so this is exact
enough). Raw lines from both devices are also mirrored to a .raw file.

Temperatures are computed from the ESP32's logged RESISTANCE via
Callendar-Van Dusen for PT1000 (ground truth), NOT from the ESP32 sketch's
Temperature print (which outputs Fahrenheit without a label and caused
confusion). Raw resistances are kept in the output too.

Usage:
    python3 dual_logger.py \
        --current-port /dev/ttyACM0 --current-baud 115200 \
        --temp-port    /dev/ttyUSB0 --temp-baud    115200 \
        --out run.csv

    # or rely on defaults:
    python3 dual_logger.py

    # ports default to auto-detect by USB vendor id -- no --*-port needed:
    python3 dual_logger.py --out run.csv

Stop with Ctrl-C. Safe for multi-hour / overnight runs (line-buffered).

Ports auto-detect by default (immune to ttyACM0<->1 / ttyUSB0<->1 renumbering).
To see what's attached:     python3 dual_logger.py --list-ports
To override:               --current-port /dev/ttyACM0 --temp-port /dev/ttyUSB0
If permission denied:      sudo usermod -aG dialout $USER   (then re-login)
"""

import sys
import os
import re
import time
import math
import argparse
import threading
from datetime import datetime

try:
    import serial
except ImportError:
    sys.exit("pyserial not installed.  pip3 install pyserial --break-system-packages")

# ---- PT1000 Callendar-Van Dusen (BOTH branches) ----
# Forward CVD (resistance as a function of temperature):
#   T >= 0 degC:  R(T) = R0 * (1 + A*T + B*T^2)                    <- quadratic
#   T <  0 degC:  R(T) = R0 * (1 + A*T + B*T^2 + C*(T-100)*T^3)    <- quartic
# The seam is exactly at R == R0 (T == 0 degC): R >= R0 is the positive branch,
# R < R0 is the sub-zero branch.
#
# We need the INVERSE (temperature from measured resistance):
#   - Positive branch is a quadratic in T -> closed-form (as before).
#   - Sub-zero branch is a quartic in T with no clean closed form. We solve it
#     with Newton-Raphson on the exact forward polynomial (seeded from the
#     positive-branch estimate). This stays faithful to the SAME equation the
#     ESP32/reference use -- no DIN inverse-polynomial approximation drift.
#
# BUG HISTORY (P0): the original res_to_c() used ONLY the positive quadratic for
# all R, so every sub-freezing reading (freezer ~-20 degC, fridge freezer
# compartment ~-18 degC) was biased a few tenths of a degree C. Raw resistance
# was always logged, so affected temps are recomputable -- this fix + a rerun of
# the stored resistances corrects them. (See docs/todo.md P0.)
_R0 = 1000.0
_A = 3.9083e-3
_B = -5.775e-7
_C = -4.183e-12   # sub-zero term only; C == 0 for T >= 0

def res_to_c(R):
    # Positive-branch closed form: solve B*T^2 + A*T + (1 - R/R0) = 0 for T.
    a, b, c = _B, _A, 1.0 - R / _R0
    disc = b * b - 4 * a * c
    t = (-b + math.sqrt(disc)) / (2 * a)
    if R >= _R0:
        return t   # T >= 0 degC: quadratic is exact, done.
    # Sub-zero: the quadratic value is only a seed. Refine on the full quartic
    # forward CVD via Newton-Raphson. Converges in a few iterations.
    #   f(T)  = R0*(1 + A*T + B*T^2 + C*(T-100)*T^3) - R
    #   f'(T) = R0*(A + 2*B*T + C*(4*T^3 - 300*T^2))
    for _ in range(50):
        f = _R0 * (1.0 + _A*t + _B*t*t + _C*(t - 100.0)*t**3) - R
        fp = _R0 * (_A + 2.0*_B*t + _C*(4.0*t**3 - 300.0*t*t))
        dt = f / fp
        t -= dt
        if abs(dt) < 1e-10:
            break
    return t

def res_to_f(R):
    return res_to_c(R) * 9.0 / 5.0 + 32.0


def _self_test():
    """Pin res_to_c() to IEC 60751 PT1000 table points spanning BOTH branches.

    These (temp_C, ohms) pairs are the standard PT1000 reference table (PT100 x10),
    an INDEPENDENT witness -- they are NOT generated by inverting our own forward
    formula, so agreement means the conversion is correct, not merely self-
    consistent. Covers well below 0 (the sub-zero branch this fix adds), the
    0 degC seam, and above.
    """
    # (temperature degC, resistance ohm) from IEC 60751 for PT1000.
    table = [
        (-40.0, 842.71),
        (-30.0, 882.22),
        (-20.0, 921.60),
        (-18.0, 929.46),
        (-10.0, 960.86),
        (  0.0, 1000.00),
        ( 10.0, 1039.03),
        ( 25.0, 1097.35),
        (100.0, 1385.06),
    ]
    worst = 0.0
    print("# self-test: res_to_c() vs IEC 60751 PT1000 table")
    for t_ref, r in table:
        t = res_to_c(r)
        err = abs(t - t_ref)
        worst = max(worst, err)
        flag = "OK " if err < 0.05 else "!! "
        branch = "sub-zero" if r < _R0 else "positive"
        print(f"#   {flag}{r:9.2f} ohm -> {t:8.3f} C  (ref {t_ref:7.1f}, "
              f"err {err:.4f}, {branch})")
    ok = worst < 0.05
    print(f"# self-test {'PASS' if ok else 'FAIL'}: worst error {worst:.4f} C "
          f"(tolerance 0.05 C)")
    return ok

# ---- shared state, updated by reader threads ----
state = {
    "amps": None,           # latest current (A)
    "amps_note": "",        # burst/decay note if present
    "res1": None, "res2": None,   # latest RTD resistances (ohm)
    "t1_f": None, "t2_f": None,   # latest temps (F) from resistance
    "fault": 0,             # 1 if a fault line seen since last temp update
}
lock = threading.Lock()
stop = threading.Event()

# regexes
cur_re   = re.compile(r"^\s*(\d+),([\d.]+),?(\w*)")     # t_ms,amps,note
res1_re  = re.compile(r"Resistance1\s*=\s*([\d.]+)")
res2_re  = re.compile(r"Resistance2\s*=\s*([\d.]+)")
fault_re = re.compile(r"[Ff]ault")


def _serial_lines(requested, role, baud, rawf, tag):
    """Yield decoded lines from the `role` device forever (until stop). RE-RESOLVES
    the port on every (re)connect, so a USB re-enumeration -- e.g. the flaky
    breadboard ESP32 coming back as a different /dev/ttyUSB number -- SELF-HEALS
    instead of the stream going dead on a stale path. Mirrors every raw line to
    rawf, tagged CUR/TMP. Shared by both readers so the reconnect logic lives once."""
    port = None
    missing_announced = False
    while not stop.is_set():
        dev = _find_port(requested, role)
        if dev is None:
            if not missing_announced:
                print(f"# {role}: device not present; waiting for it to (re)appear...")
                missing_announced = True
            time.sleep(3)
            continue
        missing_announced = False
        if dev != port:
            print(f"# {role}: {'reconnected' if port else 'connected'} on {dev}"
                  + (f" (was {port})" if port else ""))
            port = dev
        try:
            ser = serial.Serial(port, baud, timeout=1)
        except Exception as e:
            print(f"# {role} port {port} open failed: {e}; retry in 3s")
            time.sleep(3)
            continue
        try:
            buf = b""
            while not stop.is_set():
                chunk = ser.read(256)
                if not chunk:
                    continue
                buf += chunk
                while b"\n" in buf:
                    line, buf = buf.split(b"\n", 1)
                    text = line.decode("latin-1", errors="replace").rstrip("\r")
                    rawf.write(f"{time.time():.3f}\t{tag}\t{text}\n")
                    yield text
        except Exception as e:
            print(f"# {role} reader error: {e}; re-resolving + reopening")
            time.sleep(2)
        finally:
            try: ser.close()
            except Exception: pass


def reader_current(requested, baud, rawf):
    """Arduino current stream: CSV lines t_ms,amps,note."""
    for text in _serial_lines(requested, "current", baud, rawf, "CUR"):
        m = cur_re.match(text)
        if m:
            with lock:
                state["amps"] = float(m.group(2))
                state["amps_note"] = m.group(3) or ""


def reader_temp(requested, baud, rawf):
    """ESP32 RTD stream: multi-line blocks; parse Resistance1/2 + faults, pair per block."""
    pending_r1 = None
    pending_fault = 0
    for text in _serial_lines(requested, "temp", baud, rawf, "TMP"):
        if fault_re.search(text):
            pending_fault = 1
        m1 = res1_re.search(text)
        if m1:
            pending_r1 = float(m1.group(1))
        m2 = res2_re.search(text)
        if m2 and pending_r1 is not None:
            r2 = float(m2.group(1))
            try:
                t1 = res_to_f(pending_r1)
                t2 = res_to_f(r2)
            except Exception:
                t1 = t2 = None
            with lock:
                state["res1"] = pending_r1
                state["res2"] = r2
                state["t1_f"] = t1
                state["t2_f"] = t2
                state["fault"] = pending_fault
            pending_r1 = None
            pending_fault = 0


# ---- USB serial port auto-detection ----
# Linux renumbers /dev/ttyACM* and /dev/ttyUSB* across reboots/reconnects (0<->1),
# which silently points the logger at the wrong device -- the #1 startup failure.
# The Arduino (current) and the ESP32's USB-UART bridge (temps) are DIFFERENT chips,
# so we pick each by USB vendor id regardless of the /dev number. Falls back to the
# sole ttyACM*/ttyUSB* when VID is unavailable, and REFUSES to guess when ambiguous
# so we never silently log the wrong stream.
_ARDUINO_VIDS      = {0x2341, 0x2A03}            # Arduino LLC / arduino.org (Uno WiFi Rev2)
_ESP32_BRIDGE_VIDS = {0x10C4, 0x1A86, 0x0403}    # CP210x, CH340, FTDI

def _comports():
    from serial.tools import list_ports
    return list(list_ports.comports())

def list_ports_and_exit():
    ports = _comports()
    if not ports:
        print("# no serial ports found")
        return
    print("# serial ports (device  vid:pid  serial  description):")
    for p in ports:
        vid = f"{p.vid:04x}" if p.vid else "----"
        pid = f"{p.pid:04x}" if p.pid else "----"
        print(f"  {p.device}  {vid}:{pid}  {p.serial_number}  {p.description}")

def _candidates(role):
    """Serial devices that could be the `role` device: match by USB vendor id,
    else fall back to the sole ttyACM*/ttyUSB*."""
    if role == "current":
        vids, kind = _ARDUINO_VIDS, "ttyACM"
    else:
        vids, kind = _ESP32_BRIDGE_VIDS, "ttyUSB"
    ports = _comports()
    return [p for p in ports if p.vid in vids] or [p for p in ports if kind in p.device]

def _find_port(requested, role):
    """Non-fatal resolution for (re)connection: a device path, or None if not
    uniquely found. An explicit --*-port is returned as-is (may be absent -> the
    caller retries). 'auto' picks the sole candidate. Used by the reader loops."""
    if requested and requested != "auto":
        return requested
    cands = _candidates(role)
    return cands[0].device if len(cands) == 1 else None

def resolve_port(requested, role):
    """Strict STARTUP resolution: print the pick, or exit loudly if absent/ambiguous
    so we fail fast without creating an empty CSV. (Reconnection uses _find_port.)
    An explicit /dev path is passed through unchanged."""
    if requested and requested != "auto":
        return requested
    tag = "Arduino (current)" if role == "current" else "ESP32 bridge (temp)"
    cands = _candidates(role)
    if len(cands) == 1:
        print(f"# auto-detect {role}: {cands[0].device}  <- {tag}: {cands[0].description}")
        return cands[0].device
    if not cands:
        sys.exit(f"# auto-detect {role}: no {tag} found. Plug it in, or pass "
                 f"--{role}-port explicitly.  (run: dual_logger.py --list-ports)")
    sys.exit(f"# auto-detect {role}: AMBIGUOUS -- {len(cands)} candidates "
             f"[{', '.join(c.device for c in cands)}]. Pass --{role}-port explicitly.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--current-port", default="auto",
                    help="Arduino current stream. 'auto' (default) picks it by USB "
                         "vendor id -- immune to ttyACM0<->1 renumbering; or pass /dev/ttyACM0.")
    ap.add_argument("--current-baud", type=int, default=115200)
    ap.add_argument("--temp-port",    default="auto",
                    help="ESP32 temp stream. 'auto' (default) picks the USB-UART bridge; "
                         "or pass /dev/ttyUSB0.")
    ap.add_argument("--temp-baud",    type=int, default=115200)
    ap.add_argument("--out",          default=None,
                    help="output CSV. Default: a timestamped run_YYYYmmdd_HHMMSS.csv, so "
                         "forgetting --out (or replaying a stale command) can NEVER clobber "
                         "an existing capture -- it just makes a fresh unique file.")
    ap.add_argument("--rate-hz", type=float, default=10.0,
                    help="merged-row cadence (Hz). 10 Hz covers the Arduino's fastest "
                         "(100ms burst) sampling; temps (1 Hz) hold between updates.")
    ap.add_argument("--self-test", action="store_true",
                    help="run the PT1000 conversion self-test and exit (no capture).")
    ap.add_argument("--list-ports", action="store_true",
                    help="list all serial ports (device / vid:pid / serial) and exit.")
    args = ap.parse_args()

    if args.list_ports:
        list_ports_and_exit()
        sys.exit(0)
    if args.self_test:
        sys.exit(0 if _self_test() else 1)

    # Timestamped default so a forgotten/stale --out never collides with real data.
    if args.out is None:
        args.out = datetime.now().strftime("run_%Y%m%d_%H%M%S.csv")
        print(f"# no --out given; using timestamped {args.out}")

    # Resolve ports BEFORE creating any file, so a missing device fails fast
    # without leaving an empty CSV behind.
    cur_port = resolve_port(args.current_port, "current")
    tmp_port = resolve_port(args.temp_port, "temp")

    raw_path = args.out.rsplit(".", 1)[0] + ".raw"
    # Never clobber an existing capture. Multi-hour runs are expensive and
    # unrepeatable; silently appending to (old "a" mode) or overwriting an
    # existing file risks mixing two runs or destroying data. Refuse and make
    # the user pick a fresh --out. Guard BOTH the merged CSV and its .raw sidecar.
    for p in (args.out, raw_path):
        if os.path.exists(p):
            sys.exit(f"# refusing to write: {p} already exists.\n"
                     f"# pick a new --out name (this logger never overwrites or "
                     f"appends to an existing capture).")
    # Exclusive-create so a race between the check above and the open still
    # fails rather than clobbers.
    try:
        rawf = open(raw_path, "x", buffering=1)
        outf = open(args.out, "x", buffering=1)
    except FileExistsError as e:
        sys.exit(f"# refusing to write: {e.filename} already exists.")
    outf.write("unix_s,iso,current_a,current_note,"
               "t1_freezer_f,t2_fridge_f,res1_ohm,res2_ohm,fault\n")

    print(f"# current: {cur_port} @ {args.current_baud}")
    print(f"# temp:    {tmp_port} @ {args.temp_baud}")
    print(f"# merged -> {args.out}  ({args.rate_hz:g} Hz sample-and-hold)")
    print(f"# raw    -> {raw_path}")
    print("# one machine, one clock: no post-hoc alignment needed. Ctrl-C to stop.\n")

    # Readers get the ORIGINAL request (e.g. "auto"), not the resolved path, so
    # they re-resolve on every reconnect and follow a re-enumerated device.
    tc = threading.Thread(target=reader_current,
                          args=(args.current_port, args.current_baud, rawf), daemon=True)
    tt = threading.Thread(target=reader_temp,
                          args=(args.temp_port, args.temp_baud, rawf), daemon=True)
    tc.start(); tt.start()

    # Fixed-rate sample-and-hold merge: every 1/rate_hz seconds, snapshot the
    # latest current + latest temps and write one row. Simple, regular grid,
    # single clock. Current repeats when it updates slower than the row rate;
    # temps hold (1 Hz) between updates. Nothing is lost: 10 Hz >= all sources.
    period = 1.0 / args.rate_hz
    next_t = time.time()
    try:
        while True:
            next_t += period
            sleep = next_t - time.time()
            if sleep > 0:
                time.sleep(sleep)
            with lock:
                amps = state["amps"]; note = state["amps_note"]
                t1 = state["t1_f"]; t2 = state["t2_f"]
                r1 = state["res1"]; r2 = state["res2"]
                fault = state["fault"]
            if amps is None and t1 is None:
                continue  # nothing to log yet
            now = time.time()
            iso = datetime.now().isoformat(timespec="milliseconds")
            outf.write("%.3f,%s,%s,%s,%s,%s,%s,%s,%d\n" % (
                now, iso,
                ("%.3f" % amps) if amps is not None else "",
                note,
                ("%.3f" % t1) if t1 is not None else "",
                ("%.3f" % t2) if t2 is not None else "",
                ("%.2f" % r1) if r1 is not None else "",
                ("%.2f" % r2) if r2 is not None else "",
                fault,
            ))
    except KeyboardInterrupt:
        print("\n# stopping...")
        stop.set()
        time.sleep(0.5)
    finally:
        outf.close()
        rawf.close()


if __name__ == "__main__":
    main()